routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\PostController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});



Route::middleware(['auth', 'our:admin'])->group(function () {
    Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');
Route::resource('posts', PostController::class)->except('show');
Route::put('posts/{post}/complete', [PostController::class, 'complete'])->middleware('our:admin')->name('post.complete');
Route::resource('categories', CategoryController::class);
});



require __DIR__.'/auth.php';

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Post extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'user_id',
        'image',
        'is_complete',
        'category_id',
    ];

    public function categories() {

        return $this->belongsToMany(Category::class);

   }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use App\Http\Requests\PostRequest;
use App\Models\Category;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['posts'] = Post::with('categories')->get();
        // dd($data);

        return view('post.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['categories'] = Category::pluck('name', 'id');

        return view('post.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  App\Http\Requests\PostRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostRequest $request)
    {
        $path = $request->file('image')->store('images/post');
        if(!$path) {
            return redirect()->back()->with("ERROR", __("Failed to upload image"));
        }
        $user = Auth::user()->id;
        $post = Post::create([
            'user_id' => $user,
            'name' => $request->get('name'),
            'category_id' => $request->get('category_id'),
            'image' => $path
        ]);
        if(empty($post)) {
            return redirect()->back()->withInput();
        }
        return redirect()->route('posts.index')->with("SUCCESS", __("Post has been created successfully"));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
    }

    public function complete(Post $post) {

        $post->forceFill([
            'is_complete' => true
        ]);
        if($post->update()){
            return redirect()->route('posts.index')->with("SUCCESS", __('Post has been completed successfully'));
        }
        return redirect()->back()->with("ERROR", __('Failed to updated'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $data['posts'] = $post;

        return view('post.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(PostRequest $request, Post $post)
    {
        if($request->hasFile('image')) {
            if($post->image) {
                Storage::delete($post->image);
            }
            $path = $request->file('image')->store('images/post');
        }
        if($post->update([
            $post->name = $request->get('name'),
            $post->image = $path
        ])) {
            return redirect()->route('posts.index')->with('SUCCESS', __('Post has been updated successfully'));
        }
        return redirect()->back()->withInput()->with('ERROR', __('Failed to update'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        Storage::delete($post->image);
        if($post->delete()) {
            return redirect()->back()->with('SUCCESS', __('Post has been deleted successfully'));
        }
        return redirect()->back()->with('ERROR', __('Failed to delete todo'));
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/post/_form.blade.php
<div class="mb-4">
    <label class="block" for="task">Name</label>
    <input class="focus" type="text" name="name" id="name" value="{{ old('name', isset($posts) ? $posts->name : '') }}">
    <p class="text-red-600">{{ $errors->first('name') }}</p>
</div>
<div class="mb-4">
    <label class="block" for="task">Category Name</label>
    <select name="category_id" id="category_id" multiple="true">
        <option value="">Select Category</option>
        @foreach ($categories as $key => $value)
            <option value="{{ $key }}">{{ $value }}</option>
        @endforeach
    </select>
    <p class="text-red-600">{{ $errors->first('category_id') }}</p>
</div>
<div class="mb-4">
    <label class="block" for="image">Image</label>
    <input type="file" name="image" id="image">
</div>
<button class="px-4 py-2 bg-green-600" type="submit">{{ $buttonText }}</button>

resources/views/post/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Create Post') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <form action="{{ route('posts.store') }}" method="post" enctype="multipart/form-data">
                    @csrf
                    @include('post._form', ['buttonText' => __('Create')])
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/post/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Update Todo') }}
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <form action="{{ route('posts.update', $posts->id) }}" method="post" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    @include('post._form', ['buttonText' => __('Update')])
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/post/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="flex justify-between">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Post List') }}
            </h2>
            <a href="{{ route('posts.create') }}" class="px-4 py-2 bg-green-600">Create Post</a>
        </div>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <section class="container mx-auto p-6 font-mono">
                        <div class="w-full mb-8 overflow-hidden rounded-lg shadow-lg">
                            <div class="w-full overflow-x-auto">
                            <table class="w-full">
                                <thead>
                                <tr class="text-md font-semibold tracking-wide text-left text-gray-900 bg-gray-100 uppercase border-b border-gray-600">
                                    <th class="px-4 py-3">ID</th>
                                    <th class="px-4 py-3">Name</th>
                                    <th class="px-4 py-3">category Name</th>
                                    <th class="px-4 py-3">Image</th>
                                    <th class="px-4 py-3">Status</th>
                                    <th class="px-4 py-3">Action</th>
                                </tr>
                                </thead>
                                @forelse($posts as $post)
                                <tbody class="bg-white">
                                <tr class="text-gray-700">
                                    <td class="px-4 py-3 border">{{ $post->id }}</td>
                                    <td class="px-4 py-3 font-semibold border text-ms">{{ $post->name }}</td>
                                    <td class="px-4 py-3 font-semibold border text-ms">{{ $post->categories->pluck("name")->join(", ") }}</td>
                                    <td class="px-4 py-3 text-xs border">
                                        <img src="{{ asset($post->image) }}" alt="image" width="100px">
                                    </td>
                                    <td class="px-4 py-3 text-xs border">{{ $post->is_complete ? 'complete' : 'incomplete' }}</td>
                                    <td class="px-4 py-3 text-xs border">
                                        <a class="px-2 py-1 bg-yellow-500" href="{{ route('posts.edit', $post->id) }}">Edit</a>
                                        @if (!$post->is_complete)
                                            <a class="px-2 py-1 bg-green-500 complete-todo" data-confirm="Are you sure to complete this?" href="{{ route('post.complete', $post->id) }}">Complete</a>
                                        @endif
                                        <a class="px-2 py-1 bg-red-500 delete-row" data-confirm="Are you sure to delete this?" href="{{ route('posts.destroy', $post->id) }}">Delete</a>
                                    </td>
                                </tr>
                                </tbody>
                                @empty
                                <tr>
                                    <td colspan="5" class="px-4 py-3 text-center">{{ __('No Posts Found') }}</td>
                                </tr>
                                @endforelse
                            </table>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>