routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\PostController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});



Route::middleware(['auth', 'our:admin'])->group(function () {
    Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');
Route::resource('posts', PostController::class)->except('show');
Route::put('posts/{post}/complete', [PostController::class, 'complete'])->middleware('our:admin')->name('post.complete');
Route::resource('categories', CategoryController::class);
});



require __DIR__.'/auth.php';

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
    ];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Http\Requests\CategoryRequest;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['categories'] = Category::all();

        return view('category.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  App\Http\Requests\CategoryRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        $cat = Category::create([
            'name' => $request->get('name'),
        ]);

        if(empty($cat)) {
            return redirect()->back()->withInput();
        }
        return redirect()->route('categories.index')->with("SUCCESS", __("Category has been created successfully"));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, Category $category)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/category/_form.blade.php
<div class="mb-4">
    <label class="block" for="name">Category Name</label>
    <input class="focus" type="text" name="name" id="name" value="{{ old('name') }}">
    <p class="text-red-600">{{ $errors->first('name') }}</p>
</div>
<button class="px-4 py-2 bg-green-600" type="submit">{{ $buttonText }}</button>

resources/views/category/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Create Category') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <form action="{{ route('categories.store') }}" method="post">
                    @csrf
                    @include('category._form', ['buttonText' => __('Create')])
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/category/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="flex justify-between">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Category List') }}
            </h2>
            <a href="{{ route('categories.create') }}" class="px-4 py-2 bg-green-600">Create Category</a>
        </div>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <section class="container mx-auto p-6 font-mono">
                        <div class="w-full mb-8 overflow-hidden rounded-lg shadow-lg">
                            <div class="w-full overflow-x-auto">
                                <table class="w-full">
                                    <thead>
                                    <tr class="text-md font-semibold tracking-wide text-left text-gray-900 bg-gray-100 uppercase border-b border-gray-600">
                                        <th class="px-4 py-3">ID</th>
                                        <th class="px-4 py-3">Category Name</th>
                                        <th class="px-4 py-3">Action</th>
                                    </tr>
                                    </thead>
                                    @forelse($categories as $category)
                                    <tbody class="bg-white">
                                    <tr class="text-gray-700">
                                        <td class="px-4 py-3 border">{{ $category->id }}</td>
                                        <td class="px-4 py-3 font-semibold border text-ms">{{ $category->name }}</td>
                                        <td class="px-4 py-3 text-xs border">
                                            <a class="px-2 py-1 bg-yellow-500" href="{{ route('categories.edit', $category->id) }}">Edit</a>
                                            <a class="px-2 py-1 bg-red-500 delete-row" data-confirm="Are you sure to delete this?" href="{{ route('categories.destroy', $category->id) }}">Delete</a>
                                        </td>
                                    </tr>
                                    </tbody>
                                    @empty
                                    <tr>
                                        <td colspan="3" class="px-4 py-3 text-center">{{ __('No Catgories Found') }}</td>
                                    </tr>
                                    @endforelse
                                </table>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>